name: workflow-calling
on: 
    push: 
        branches: 
            - feature/assignment1code
    pull_request: 
        branches: 
            - feature/assignment1code
        types: [opened, closed]
    workflow_dispatch: 
    
jobs:
    workflow-calling:
      uses: ./.github/workflows/deploy-java-app.yaml 
      #secrets: 
        #AZ_WEB_APP_PUBLISH_PROFILE_PS: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AS }}
      with:
        java_distribution: adopt
        java_version: '17'
        upload_artifact_name: java-app-war-file-rs
        upload_artifact_path:  '/java-webapp/target/*.jar'
        download_artifact_name: java-app-war-file-rs
        webapp_name: java-app
        slot-name: dev
        
