name: workflow-calling
on: 
    push: 
        branches: 
            - feature/assignment1code
    pull_request: 
        branches: 
            - feature/assignment1code
        types: [opened, closed]
    workflow_dispatch: 
    
jobs:
    workflow-calling:
      uses: ./.github/workflows/deploy-java-app.yaml 
      #secrets: 
        #AZ_WEB_APP_PUBLISH_PROFILE_PS: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AS }}
      with:
        java_distribution: adopt
        java_version: '17'
        upload_artifact_name: java-app
        upload_artifact_path:  '/hello-world-webapp/target/*.war'
        download_artifact_name: java-app
        webapp_name: java-app
        slot-name: production
        
