
name: deploy java webapp
on: 
    workflow_call: 
      inputs:
        java_distribution:
          description: Java Distribution
          required: true
          type: string
        java_version:
          description: Java Version
          required: true
          type: string
        upload_artifact_name:
          description: Name of the artifact to upload.
          required: true
          type: string
        upload_artifact_path:
          description: Path that describes what to upload.
          required: true
          type: string
        download_artifact_name:
          description: Name of the artifact to download.
          required: true
          type: string
        webapp_name:
          description: Name of azure web application.
          required: true
          type: string
        slot-name:
          description: Name of the slot of azure web application.
          required: true
          type: string
      #secrets:
        #AZ_WEB_APP_PUBLISH_PROFILE_PS:
         # required: true
          #description: Webapp Publish Profile
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning the repo
              uses: actions/checkout@v3
            - name: List repository contents
              run: ls -la

            - name: Dependencies Cache 
              uses: actions/cache@v2
              with:
                path: ~/.maven
                key: ${{ runner.os }}-maven
            - name: java env setup
              uses: actions/setup-java@v3
              with:
                distribution: ${{ inputs.java_distribution }} #adopt
                java-version: ${{ inputs.java_version }} #'17'
            - name: code build
              run: |
                ls -la hello-world-webapp  # Check if the directory exists
                cd hello-world-webapp
                mvn clean install
            - run: |
                echo ${{ github.workspace }} #Path: /home/runner/work/build-deploy-sample/build-deploy-sample
                ls
                cd hello-world-webapp/target
                echo "Inside target"
                ls
            - name: upload war file 
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ inputs.upload_artifact_name }} #java-app-war-file
                  path: '${{ github.workspace }}${{ inputs.upload_artifact_path }}' # ${{ github.workspace }}'/target/*.jar
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download Artifact from Workflow
          uses: actions/download-artifact@v4
          with:
             name: ${{ inputs.download_artifact_name }} #java-app-war-file
        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ inputs.webapp_name }} #'ga-wa-sc-01'
            publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C185F53252714845879E112C029AD896}}
            package: '*.jar'
            slot-name: ${{ inputs.slot-name }}
