name: Deploy Java Application

on:
  workflow_call:
    inputs:
      app-name:
        description: 'Name of the Azure Web App'
        required: true
        type: string
      resource-group:
        description: 'Azure Resource Group'
        required: true
        type: string
      java-version:
        description: 'Java version to use'
        required: true
        type: string
      publish-profile:
        description: 'Azure Web App publish profile'
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ inputs.java-version }}

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.app-name }}
          slot-name: production
          publish-profile: ${{ inputs.publish-profile }}
          package: target/*.war
